package javax.xml.bind.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import javax.validation.Constraint;
import javax.validation.Payload;
import javax.xml.bind.annotation.validation.MaxOccursValidator;

/**
 * This annotation class is used to support the XSD 'maxOccurs' attribute in XML
 * Schema files generated by JAXB RI.
 * 
 * @author Waldemar Hummer (hummer@infosys.tuwien.ac.at)
 * @since JAXB-Facets version 0.1
 */
@Target(value = { ElementType.FIELD, ElementType.METHOD })
@Retention(value = RetentionPolicy.RUNTIME)
@Documented
@Constraint(validatedBy = MaxOccursValidator.class)
public @interface MaxOccurs {

    public static final String VALIDATION_MESSAGE_KEY = "javax.xml.bind.annotation.MaxOccurs.message";

    long value();

    /** message used for JSR-303 bean validation. */
    String message() default "{" + VALIDATION_MESSAGE_KEY + "}";

    /** groups used for JSR-303 bean validation. */
    Class<?>[] groups() default {};

    /** payload used for JSR-303 bean validation. */
    Class<? extends Payload>[] payload() default {};
}